name: test-alerts-ga
run-name: ${{ github.actor }} testing koel workflow
on:
  push:
    branches:
      - main

jobs:
  test-alerts:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: 'main'
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
        
      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.1'
          
      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
        
      - name: Install dependencies
        run: R -e "renv::install()"
          
      - name: Run script
        run: Rscript s2_test_alerts.R

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add current_alerts_data.csv
          git add cache
          git commit -m "`date +\"%Y-%m-%d\"` test alerts"
          git push origin