name: test-alerts-ga
run-name: ${{ github.actor }} testing koel workflow
on:
  push:
    branches:
      - main

jobs:
  test-alerts:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: 'main'
          
      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.1'    
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install RTools
        uses: r-windows/install-rtools@master
        
      - name: Install chrome
        uses: browser-actions/setup-chrome@v1
        
      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
        
      - name: Run script
        run: Rscript s2_test_alerts.R
      
      - name: Commit results
        run: |
          $cstzone = [System.TimeZoneInfo]::FindSystemTimeZoneById("Cen. Australia Standard Time")
          $csttime = [System.TimeZoneInfo]::ConvertTimeFromUtc((Get-Date).ToUniversalTime(), $cstzone)
          Get-Date $csttime.AddHours(-1) -f "dd\\MM\\yyyy HH:mm"
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add cache
          git commit -m "test alerts ($csttime -f 'dd\\MM\\yyyy HH:mm')"
          git push origin